// typing.config.ts
import { WordSet } from "../interface/typing.interface";

// 单词及其中文释义
export const WORDS_WITH_MEANINGS: Record<string, string> = {
  'apple': '苹果',
  'beautiful': '美丽的',
  'computer': '计算机',
  'developer': '开发者',
  'experience': '经验',
  'fantastic': '极好的',
  'github': 'GitHub平台',
  'hello': '你好',
  'internet': '互联网',
  'javascript': 'JavaScript编程语言',
  'knowledge': '知识',
  'learning': '学习',
  'mountain': '山',
  'network': '网络',
  'open source': '开源',
  'programming': '编程',
  'quality': '质量',
  'react': 'React框架',
  'software': '软件',
  'technology': '技术',
  'unique': '独特的',
  'virtual': '虚拟的',
  'website': '网站',
  'xenial': '友好的',
  'youtube': 'YouTube视频平台',
  'zealous': '热情的',
  'algorithm': '算法',
  'backend': '后端',
  'cloud': '云',
  'database': '数据库',
  'frontend': '前端',
  'git': 'Git版本控制',
  'html': 'HTML标记语言',
  'css': 'CSS样式表',
  'typescript': 'TypeScript编程语言',
  'python': 'Python编程语言',
  'java': 'Java编程语言',
  'rust': 'Rust编程语言',
  'go': 'Go编程语言',
  'swift': 'Swift编程语言',
  'kotlin': 'Kotlin编程语言',
  'ruby': 'Ruby编程语言',
  'php': 'PHP编程语言',
  'docker': 'Docker容器平台',
  'kubernetes': 'Kubernetes编排平台',
  'aws': '亚马逊云服务',
  'azure': '微软云平台',
  'mongodb': 'MongoDB数据库',
  'postgresql': 'PostgreSQL数据库',
  'redis': 'Redis缓存数据库',
  'asynchronous': '异步的',
  'callback': '回调函数',
  'closure': '闭包',
  'compiler': '编译器',
  'dependency': '依赖',
  'encapsulation': '封装',
  'framework': '框架',
  'functional': '函数式的',
  'generics': '泛型',
  'immutable': '不可变的',
  'inheritance': '继承',
  'interface': '接口',
  'lambda': 'Lambda表达式',
  'middleware': '中间件',
  'namespace': '命名空间',
  'optimization': '优化',
  'polymorphism': '多态',
  'queue': '队列',
  'recursion': '递归',
  'singleton': '单例模式',
  'thread': '线程',
  'variable': '变量',
  'webpack': 'Webpack打包工具',
  'xml': 'XML标记语言',
  'yaml': 'YAML数据格式',
  'zero': '零',
  'boolean': '布尔值',
  'constant': '常量',
  'debugger': '调试器',
  'event loop': '事件循环',
  'factory': '工厂模式',
  'garbage': '垃圾回收',
  'hoisting': '变量提升',
  'iterator': '迭代器',
  'json': 'JSON数据格式',
  'keyword': '关键字',
  'lexical': '词法的',
  'memoization': '记忆化',
  'nullable': '可空的',
  'object': '对象'
};

// 获取单词的中文释义
export const getWordMeaning = (word: string): string => {
  return WORDS_WITH_MEANINGS[word.toLowerCase()] || '暂无释义';
};

// 官方词汇集 1 - 基础词汇
export const OFFICIAL_WORD_SET_1: WordSet = {
  id: -2,
  name: "基础词汇 (50词)",
  words: [
    'apple', 'beautiful', 'computer', 'developer', 'experience',
    'fantastic', 'github', 'hello', 'internet', 'javascript',
    'knowledge', 'learning', 'mountain', 'network', 'open source',
    'programming', 'quality', 'react', 'software', 'technology',
    'unique', 'virtual', 'website', 'xenial', 'youtube',
    'zealous', 'algorithm', 'backend', 'cloud', 'database',
    'frontend', 'git', 'html', 'css', 'typescript',
    'python', 'java', 'rust', 'go', 'swift',
    'kotlin', 'ruby', 'php', 'docker', 'kubernetes',
    'aws', 'azure', 'mongodb', 'postgresql', 'redis'
  ],
  isOfficial: true,
  createdAt: new Date().toISOString()
};

// 官方词汇集 2 - 编程术语
export const OFFICIAL_WORD_SET_2: WordSet = {
  id: -1,
  name: "编程术语 (40词)",
  words: [
    'asynchronous', 'callback', 'closure', 'compiler', 'dependency',
    'encapsulation', 'framework', 'functional', 'generics', 'immutable',
    'inheritance', 'interface', 'lambda', 'middleware', 'namespace',
    'optimization', 'polymorphism', 'queue', 'recursion', 'singleton',
    'thread', 'variable', 'webpack', 'xml', 'yaml',
    'zero', 'boolean', 'constant', 'debugger', 'event loop',
    'factory', 'garbage', 'hoisting', 'iterator', 'json',
    'keyword', 'lexical', 'memoization', 'nullable', 'object'
  ],
  isOfficial: true,
  createdAt: new Date().toISOString()
};